export const BASE_COLORS = {
  black: '#000000',
  white: '#FFFFFF',
  riverStyx: '#161622',
  blueRibbon: '#0066FF',
  blackHowl: '#1C1C1E',
  blackVelvet: '#232533',
  blackRock: '#2A2C3C',
  darkGunmetal: '#1E1E2D',
  error: '#FF3B30',
  success: '#34C759',
  outlawedOrange: '#A2A2A7',
  lighthouse: '#F4F4F4',
  dugong: '#707070',
  cornflowerBlue: '#34343433',
  spinelStoneBlack: '#27273A',
  sleet: '#8B8B94',
  seriousCloud: '#7E848D',
};

export const colors = {
  error: BASE_COLORS.error,
  label: BASE_COLORS.outlawedOrange,
  placeholderText: BASE_COLORS.outlawedOrange,
  activityIndicator: BASE_COLORS.blueRibbon,
  loadingIndicatorBg: BASE_COLORS.cornflowerBlue,
  signUpFooterText: BASE_COLORS.dugong,
  signUpNavigationText: BASE_COLORS.blueRibbon,
  transactionItemSubTitle: BASE_COLORS.outlawedOrange,
  virtualCardBg: BASE_COLORS.blackRock,
  virtualCardLabel: BASE_COLORS.outlawedOrange,
  homeSeeAll: BASE_COLORS.blueRibbon,
  homeWelcome: BASE_COLORS.seriousCloud,
  modalOverlay: 'rgba(0, 0, 0, 0.3)',
  pickerModalDoneText: BASE_COLORS.blueRibbon,
  light: {
    solidBtnTitle: BASE_COLORS.white,
    solidBtnBg: BASE_COLORS.blueRibbon,
    inputText: BASE_COLORS.blackHowl,
    descriptionText: BASE_COLORS.outlawedOrange,
    searchInputBg: BASE_COLORS.lighthouse,
    searchInputText: BASE_COLORS.darkGunmetal,
    appBg: BASE_COLORS.white,
    appHeaderIconBg: BASE_COLORS.lighthouse,
    appHeaderTitle: BASE_COLORS.darkGunmetal,
    inputBorder: BASE_COLORS.lighthouse,
    actionItemText: BASE_COLORS.darkGunmetal,
    actionItemBg: BASE_COLORS.lighthouse,
    transactionItemTitle: BASE_COLORS.darkGunmetal,
    transactionItemAvatarBg: BASE_COLORS.lighthouse,
    transactionItemAmount: BASE_COLORS.darkGunmetal,
    homeUsername: BASE_COLORS.darkGunmetal,
    homeTransactionHeader: BASE_COLORS.darkGunmetal,
    homeSearchBg: BASE_COLORS.lighthouse,
    pickerModalIOSContainer: BASE_COLORS.white,
  },
  dark: {
    solidBtnTitle: BASE_COLORS.white,
    solidBtnBg: BASE_COLORS.blueRibbon,
    inputText: BASE_COLORS.white,
    descriptionText: BASE_COLORS.dugong,
    searchInputBg: BASE_COLORS.blackVelvet,
    searchInputText: BASE_COLORS.white,
    appBg: BASE_COLORS.riverStyx,
    appHeaderIconBg: BASE_COLORS.darkGunmetal,
    appHeaderTitle: BASE_COLORS.white,
    inputBorder: BASE_COLORS.blackVelvet,
    actionItemText: BASE_COLORS.outlawedOrange,
    actionItemBg: BASE_COLORS.darkGunmetal,
    transactionItemTitle: BASE_COLORS.white,
    transactionItemAvatarBg: BASE_COLORS.darkGunmetal,
    transactionItemAmount: BASE_COLORS.white,
    homeUsername: BASE_COLORS.white,
    homeTransactionHeader: BASE_COLORS.white,
    homeSearchBg: BASE_COLORS.darkGunmetal,
    pickerModalIOSContainer: BASE_COLORS.darkGunmetal,
  },
};
