export const BASE_COLORS = {
  black: '#000000',
  white: '#FFFFFF',
  riverStyx: '#161622',
  blueRibbon: '#0066FF',
  blackHowl: '#1C1C1E',
  blackVelvet: '#232533',
  darkGunmetal: '#1E1E2D',
  error: '#FF3B30',
  success: '#34C759',
  outlawedOrange: '#A2A2A7',
  lighthouse: '#F4F4F4',
  dugong: '#707070',
  cornflowerBlue: '#34343433',
};

export const colors = {
  error: BASE_COLORS.error,
  label: BASE_COLORS.outlawedOrange,
  inputBorder: BASE_COLORS.lighthouse,
  placeholderText: BASE_COLORS.outlawedOrange,
  activityIndicator: BASE_COLORS.blueRibbon,
  loadingIndicatorBg: BASE_COLORS.cornflowerBlue,
  light: {
    solidBtnTitle: BASE_COLORS.white,
    solidBtnBg: BASE_COLORS.blueRibbon,
    inputText: BASE_COLORS.blackHowl,
    descriptionText: BASE_COLORS.outlawedOrange,
    searchInputBg: BASE_COLORS.lighthouse,
    searchInputText: BASE_COLORS.darkGunmetal,
  },
  dark: {
    solidBtnTitle: BASE_COLORS.white,
    solidBtnBg: BASE_COLORS.blueRibbon,
    inputText: BASE_COLORS.white,
    descriptionText: BASE_COLORS.dugong,
    searchInputBg: BASE_COLORS.blackVelvet,
    searchInputText: BASE_COLORS.white,
  },
};
