name: Create all environment builds

on:
  push:
    branches: ['feat/eas-examples']

jobs:
  # ------------------------------
  # 🔥 DEVELOPMENT BUILDS
  # ------------------------------
  android_development:
    type: build
    params:
      platform: android
      profile: development

  ios_development:
    type: build
    params:
      platform: ios
      profile: development

  # ------------------------------
  # 🔥 STAGING / PREVIEW BUILDS
  # ------------------------------
  android_preview:
    type: build
    params:
      platform: android
      profile: preview

  ios_preview:
    type: build
    params:
      platform: ios
      profile: preview
